cache: pip
language: python

python:
  - "2.7"

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme

env:
  matrix:
    - TEST_DIR=en
    - TEST_DIR=ko

before_script:
  - cd $TEST_DIR
  - make html

script:
  - make linkcheck

after_script:
  - cd ..
