name: Slash command dispatch

on:
  issue_comment:
    types: [created, edited]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch slash command
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        commands: |
          preview
          teardown
        permission: write