# Inputs:
#  client_payload.pull_request.number - PR number

name: Delete PR Staging Environment

on:
  repository_dispatch:
    types: [teardown-command]

env:
  DOMAIN: ${{ format('{0}-{1}-pr{2}.surge.sh', github.event.repository.owner.login, github.event.repository.name, github.event.client_payload.pull_request.number) }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Dump context
      env:
        CONTEXT: ${{ toJson(github) }}
      run: |
        echo "Context: $CONTEXT"
    - name: Teardown surge.sh
      run: npx surge teardown ${{ env.DOMAIN }}
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      
    - name: Add comment to PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.client_payload.pull_request.number }}
        body: ${{ format('Tore down {0}', env.DOMAIN) }}